repos:
- repo: local
  hooks:
    - id: ruff
      name: ruff
      entry: ruff check .
      language: system
      pass_filenames: false
    - id: mypy
      name: mypy
      entry: mypy --ignore-missing-imports .
      language: system
      pass_filenames: false
    - id: pytest
      name: pytest
      entry: pytest -q
      language: system
      pass_filenames: false
